### PR TITLE
Dynamic redirect URL

### PR DESCRIPTION
**Pull request by girlpunk**
Add support for dynamically setting the redirect URL when creating a MonzoAPI Instance.

### CODE REVIEW

**Comment by pawelad** [comment]
Wow, thanks for all the PRs, I'll try to go through them shortly.

In the meantime, would you mind explaining how are these changes (this one and #17) helping you and look at Travis CI / Coveralls for more immediate feedback?

**Comment by girlpunk** [comment]
No problem, glad I could help :)

I made the changes here and in #17 to allow better handling of account management in a permanent installation (and to make it more user-friendly for non-developers). Copying the auth token from a Github URL is fine for you and me, but might be a bit more difficult for the average Monzo user. This would allow a web app to use it's own URL and receive the tokens directly (as origanally intended by OAuth)

This one is failing as the unit test is still referencing the `config.REDIRECT_URI` attribute, which no longer exists. I'll get a fix for that pushed shortly.

**Comment by girlpunk** [comment]
Unit tests fixed, though I'm not sure what coveralls is doing at the moment...

**Comment by pawelad** [comment]
> Copying the auth token from a Github URL is fine for you and me, but might be a bit more difficult for the average Monzo user. This would allow a web app to use it's own URL and receive the tokens directly (as origanally intended by OAuth)

My only note to this is putting too much variables in class init kwargs, especially since that value already _is_ configurable (albeit less obvious / user friendly).

I believe that there is _some_ value in making values like that non-trivial to change (in this case via environment variable and not an init kwarg), to keep the 'regular' users from changing it, but... this might be a bad example of it : )

**Comment by pawelad** [comment]
Yeah, I'm still not convinced it should be an init kwarg. What do you think about moving it to a class attribute instaed?

```python
monzo_api = MonzoAPI()
monzo_api.redirect_url = 'custom_url'
```

That would make it obvious / easy to change and would not 'pollute' the init kwargs.

I believe I did that in the beginning but them moved it out thinking some other piece of code would need to access it as well.

---

And please, do let me know what you think - I'm not married to any of this and you _clearly_ use this library more then I do at the moment (I moved out of UK a while ago), so I might as accept anything that makes your life easier ; -)

**Comment by girlpunk** [comment]
That's a nice solution, but would have problems when the init function calls `_get_oauth_token`, as it uses the URL. Could we move the key loading/retrieval to a seperate function that would need to be called by the user? Would also allow us to clean up more stuff from the init kwargs.

**Comment by cyberjacob** [comment]
That's a nice solution, but would have problems when the init function calls `_get_oauth_token`, as it uses the URL. Could we move the key loading/retrieval to a seperate function that would need to be called by the user? Would also allow us to clean up more stuff from the init kwargs.

**Comment by bartonp** [comment]
You can have it as a module level attribute as it currently is as well, so you can override it before the init. Granted, this doesn't resolve if you want to be running multiple instances of pymonzo with different redirect uri's though.

```python
import pymonzo

# Edit pymonzo redirect uri before init
pymonzo.monzo_api.config.PYMONZO_REDIRECT_URI = 'http://127.0.0.1:8080/monzo/auth'
pymonzo.monzo_api.config.REDIRECT_URI = 'http://127.0.0.1:8080/monzo/auth'
```

**Comment by pawelad** [comment]
First of all, sorry for replying so late. You took the time to contribute, and I didn’t take the time to reply. The library was essential not supported since ~2017. I had some free time recently though and decided to give it some love and release v1.0.0

This should be fixed now so I'm gonna go ahead and close it.

Once again, I'm very sorry for not reviewing this earlier.

**Pull request closed without merging**
