### PR TITLE
Added pot list

### PR DESCRIPTION
**Pull request by Boeeerb**
Pots are also available in the API, this allows access to this information

### CODE REVIEW

**Comment by pawelad** [comment]
Awesome, thanks for the PR!

The CI failure is because of `flake8` (you can see the actual errors in Travis CI log). I'll also need the test for this endpoint, along with the [`vcrpy`](https://github.com/kevin1024/vcrpy) cassete before I merge this - you can either do that yourself (I'll be happy to help) or leave it to me (which will probably take a little bit more time), entirely up to you.

Related - do you know if there are any more new endpoints I'm missing? I might just add them all and do a release of [monz](https://github.com/pawelad/monz/) as well.

**Comment by Boeeerb** [comment]
I just read the travis error, seems to just be an extra blank line and some whitespace, as for the cassette - I honestly can say I haven't ever used it! So it would no doubt be quicker for you?

I have only noticed the pots endpoint not integrated to date. They only backported pots in the API due to delaying the new API - https://monzo.com/blog/2018/01/12/api-update/

**Comment by pawelad** [comment]
>  just read the travis error, seems to just be an extra blank line and some whitespace

Yup, nothing major : )

> as for the cassette - I honestly can say I haven't ever used it! So it would no doubt be quicker for you?

As I said, completely up to you - I can leave it up to you (if you want to learn about ` vcrpy` for example) or try to pick it up on one of the next weekends (I don't mind, I just might not find the time in the near future).

> I have only noticed the pots endpoint not integrated to date. They only backported pots in the API due to delaying the new API - monzo.com/blog/2018/01/12/api-update

Ah, I see. Thanks for the link - I moved out of UK a while ago so I'm not as up to date (or a regular user) as I used to be.

**Comment by pawelad** [comment]
OK, I just noticed that #13 implements the same endpoint and is already merged - closing in favour of it.

**Comment by Boeeerb** [comment]
No worries! I just didn't get the time to sort this one out. I will have a play with #13 update and also update my guide using your library - https://boeeerb.co.uk/creating-a-monzo-pot-epaper-tracker/

Thanks for all the work you've put in to this project!

**Comment by pawelad** [comment]
> No worries! I just didn't get the time to sort this one out.

Yeah, same with me... ; )

>  I will have a play with #13 update and also update my guide using your library - https://boeeerb.co.uk/creating-a-monzo-pot-epaper-tracker/

Yeah, it's tested and should work as expected if you install `pymonzo` from master.

I also finally found time and added missing tests and taken care of a couple of other things, and am planning on a release later today. I'll ping you when that happens : )

And I really liked the blog post, great stuff 👍 

> Thanks for all the work you've put in to this project!

Thanks for using and trying to improve it : -)

**Comment by pawelad** [comment]
Released in [v0.11.0](https://github.com/pawelad/pymonzo/releases/tag/v0.11.0)

**Pull request closed without merging**
