### PR TITLE
Add support for adding/retrieving token data as a dict

### PR DESCRIPTION
**Pull request by girlpunk**

### CODE REVIEW

**Comment by girlpunk** [comment]
@pawelad I don't know enough about how you're running your unit tests to make this work. Can you make any sense of the logs from 21117ad?

**Comment by pawelad** [comment]
@cyberjacob Yeah, all the auth `__init__` tests are really messy and I really don't like them. I'll be happy to help with the tests, but would you mind expanding on the use cases for:

1. adding `token_data` kwarg
2. moving `default_token_save` out of the class

I can see the use cases for both and am not against it, I just want to make sure that this is the way to go.

---

I think I'm OK with 1), although ideally I'd rewrite this whole messy `a) b) c)...` thingy anyway, but I'm not sure how I feel about 2) - is the only use case to provide your own? If that's the case then wouldn't creating your own class that inherits from `MonzoAPI` and reimplements that method be better / cleaner / work right now?

**Comment by girlpunk** [comment]
Thinking about it in more detail, subclassing would probably make more sense. In which case, what would you think about moving the token loading into a separate function which would need to be called when initializing the library? It would allow it to be more easily overridden, and would also be needed for your suggestion on #16.

**Comment by cyberjacob** [comment]
Thinking about it in more detail, subclassing would probably make more sense. In which case, what would you think about moving the token loading into a separate function which would need to be called when initializing the library? It would allow it to be more easily overridden, and would also be needed for your suggestion on #16.

**Comment by pawelad** [comment]
First of all, sorry for replying so late. You took the time to contribute, and I didn’t take the time to reply. The library was essential not supported since ~2017. I had some free time recently though and decided to give it some love and release v1.0.0

This should be fixed now so I'm gonna go ahead and close it.

Once again, I'm very sorry for not reviewing this earlier.

**Pull request closed without merging**
