### PR TITLE
v2 API for Pots

### PR DESCRIPTION
**Pull request by girlpunk**
Documentation hasn't been released yet, but the `/pots`, `/pots/{id}/deposit` and `/pots/{id}/withdraw` API endpoints are now live. These can be used to list pots and transfer funds between the main amount and each pot. I've also fixed/added the unit tests for them, but haven't added a change log entry yet.

I wasn't sure how you would want the deposit and withdraw functions implemented, as there's not really any like this at the moment. I did them the way I would personally use them, but feel free to suggest changes.

### CODE REVIEW

**Comment by girlpunk** [comment]
Apparantly I forgot to add a unit test for `/pots/{id}`

**Comment by girlpunk** [comment]
ok, unit test added

**Comment by bartonp** [comment]
My suggestion would be to move the API calls of withdrawing and depositing to monzo_api, keeping the context variable on the pots. You then have a couple of helper functions on MonzoPot that just calls the correct function via context. You have the benefits of if you know the pot id and account id, you can just authenticate and do your deposit/withdrawal, and if you don't you can go through the API and still being able to do `pot.withdraw`.

This means without having to call the API, you could for a cli application use something like:
```
penny_a_day.py --account acc_0000000000000000000000 --pot pot_0000000000000000000000 --amount 125
```
**EDIT:** Question - why have you added `id = None`, `amount = None`, etc... onto the classes? Is that to have intellisense?

**Comment by girlpunk** [comment]
@bartonp That makes sense, though should the API call functions not be static functions in the `MonzoPot` class, as that's what they actually operate on?

And yes; `id`, `amount`, etc. were added for PyCharm's version of intellisense.

**Comment by bartonp** [comment]
Cool. For getting intellisense working with PyCharm, you could have a look at [this](https://github.com/bartonp/pymonzo/blob/master/src/pymonzo/api_objects.pyi). I'll look at cleaning it up and doing the other items for the current build of pymonzo.

They shouldn't be static functions as you still need to access the pot when going through the helper function. So when you go through the helper on the pot, you only need to specify the amount, and account id. This is because you already know the pot id, from `self.id`.

**Comment by pawelad** [comment]
First of all, sorry for replying so late. You took the time to contribute, and I didn’t take the time to reply. The library was essential not supported since ~2017. I had some free time recently though and decided to give it some love and release v1.0.0

This should be fixed now so I'm gonna go ahead and close it.

Once again, I'm very sorry for not reviewing this earlier.

**Pull request closed without merging**
