### PR TITLE
Add support for profile API call

### PR DESCRIPTION
**Pull request by girlpunk**
Currently not able to test, as I don't have any API credentials with the `monzo_app` scope. However, the endpoint has been confirmed by Nicholas Robinson-Wall (Monzo Staff) on Slack.

### CODE REVIEW

**Comment by pawelad** [comment]
@cyberjacob Thanks very much for this! Regarding the tests and `vcrpy`, you would have to record an actual API response which might be hard given the lack of API credentials ; -)

Hopefully I'll take care of it this week, merge it and release a new version.

**Comment by girlpunk** [comment]
Ah, that would explain it. I've got a sample response, but I'm not sure if it contains all the attributes or just the ones being discussed, if that makes a difference?

**Comment by pawelad** [comment]
You would need to convert it to `vcrpy` [cassete format](https://github.com/pawelad/pymonzo/blob/master/tests/cassettes/TestMonzoAPI.test_class_whoami_method.yaml), so it's probably easier to record a real one and obfuscate the data, the same way I did all the other.
Like I said, this requires valid API credentials so if you don't have any then you'll have to wait for me to find half an hour of free time ; )

**Comment by pawelad** [comment]
Really sorry to get back to this so late - the past couple of weeks were crazy.

I wanted to get this sorted out and merged but I'm having trouble actually getting anything from that endpoint - both in the code and in [Monzo API Playground](https://developers.monzo.com/api/playground) I'm getting a:

```json
{
  "code": "bad_request.convert_scope.unexpected",
  "message": "Unexpected conversion from V2 scope to V1 scope",
  "params": {
    "scope_namespace": "user"
  }
}
```

when trying to access `/profile`. Do you maybe know what's that about? Does that endpoint work for you? Did you had to do anything to make it work?

**Comment by girlpunk** [comment]
That would be a permissions error, looks like we might have to wait until Monzo makes that endpoint officially available before it can be added.

**Comment by pawelad** [comment]
Yeah, it could be a number of things - a flag that has to be explicitly set on the user by Monzo or a required API version header (GitHub style). It's not documented and I haven't seen the Slack conversation so I can only guess at this point.

I'm going to leave this open so feel free to update it if you'll get any more information (or confirm that the call works, for example via Monzo API Playground).
This all could also mean that they will stabilize the API on their side and actually release v1.0.

And again, thanks for the contribution and sorry for the late reply.

**Comment by girlpunk** [comment]
Monzo has mentioned that this endpoint is being deprecated, so not much point it adding support for it.

**Comment by pawelad** [comment]
OK, thanks for letting me know!

**Pull request closed without merging**
